/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_dwm_control_mainControl */

#ifndef _Included_com_dwm_control_CInterface
#define _Included_com_dwm_control_CInterface
#include <jni.h>
#include "BaseDefine.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_interface
 * Method:    init
 * Signature: ()V
 */

DFJNIBool Java_com_dwm_base_CInterface_Init(DFJNIEc, jint iBaseWidth, jint iBaseHight, jint nKeyFrameInterval, jint ifpsNum);
DFJNIBool Java_com_dwm_base_CInterface_RequestConnectToServer(DFJNIEc, jstring strServerAddr, jint iPort);
DFJNIBool Java_com_dwm_base_CInterface_SendBuff(DFJNIEc, jint iType, jbyteArray pBuff, jlong lLen, jint iW, jint iH);
DFJNIBool Java_com_dwm_base_CInterface_RequestToScan(DFJNIEc);
DFJNIBool Java_com_dwm_base_CInterface_RequestToStopScan(DFJNIEc);
DFJNIBool Java_com_dwm_base_CInterface_RequestToPay(DFJNIEc);
DFJNIInt Java_com_dwm_base_CInterface_GetSendBuffCount();


#ifdef __cplusplus
}
#endif
#endif
